### ISSUE TITLE
Benchmarks ?

### ISSUE THREAD

**Issue by stuaxo** [ezag/pyeuclid#23]
Hi,
   Thanks for pyeuclid.   Has anyone done any benchmarking on pyeuclid vs euclid ?
While I assume it is faster for many operations, but maybe after only a certain amount - it would definitely be interesting to see.

Cheers
S

**Comment by dov** [comment]
pyeuclid and euclid are the same project under different names.

npeuclid, which I wrote, on the other hand is another project, and it should be a magnitude or two faster than pyeuclid (depending on what you do...). If someone believes that is not fast enough, then it shouldn't be too difficult to turn npeuclid into torcheuclid based on pytorch.

**Comment by stuaxo** [comment]
Thanks, this is my fault for having all of those open from pypi at the same time and writing this in the wrong project  - meant to write this in npeuclid... thanks for the insight.
